### PR TITLE
Add 2021 Build API roadmap

### PR DESCRIPTION
**Pull request by comius**

### CODE REVIEW

**Review by sventiffe — APPROVED** [review]

**Review by c-mita — APPROVED** [review]

**Review by oquenchil — APPROVED** [review]
LGTM

**Comment by sventiffe** [comment]
The link on https://bazel.build/roadmap.html to https://bazel.build/roadmaps/build-api.md results in a 404. 

Now that I've seen it, I assume that the link target needs to point to .html and not .md.

**Comment by gregestren** [comment]
Ha, I just filed https://github.com/bazelbuild/bazel-website/pull/293!

**Comment by gregestren** [comment]
There's actually some subtlety here. If you browse from GitHub, `.md`. is correct. If you browse from docs.bazel.build, `.html` is correct.

I don't think we should break the latter. But I do accept people will browse from the former.

**Pull request merged**
