### PR TITLE
Update Tweag Community Experts Description

### PR DESCRIPTION
**Pull request by TC1211**
New PR to update Tweag's description on the Community Experts page. Following on from https://github.com/bazelbuild/bazel-website/pull/228

### CODE REVIEW

**Comment by TC1211** [comment]
@googlebot I signed it!

**Comment by hicksjoseph** [comment]
It is okay as-is, but it would be great to rephrase the "they're experts at" part (and maybe the whole thing) so that it doesn't sound like Google is endorsing Tweag.

**Comment by TC1211** [comment]
Noted. Thanks Joe. I will pass this along internally and get back to you soonest.

**Comment by TC1211** [comment]
Hi @hicksjoseph, thank you for your patience. We have reworked the description to more closely highlight our value proposition and avoid vague wording. Please let us know if this is ok?

**Pull request merged**
