### PR TITLE
Use new Bazel logo and colors

### PR DESCRIPTION
**Pull request by steren**
noeeczre6zo

this change focuses on the logo, future changes will focus on the content and layout.

### CODE REVIEW

**Comment by davidzchen** [comment]
The logo text on the navbar looks a bit out of proportion, specifically, a bit too large. Can you tweak it so that the proportions are more similar to that of other Google logos, such as the Firebase logo in the navbar of its site? https://firebase.google.com/

**Comment by steren** [comment]
@davidzchen I changed the navbar logo size.
Here is a screenshot: 
mmsxfrgsf8u

**Comment by davidzchen** [comment]
Thanks, Steren! Really liking the new logo. We might want to also update the typefaces for the rest of the site to better match the the logo typeface. Let's make those tweaks as follow-up changes.

**Comment by steren** [comment]
Thanks.

We should not use Product Sans for the body font. It is only intended for product titles as far as I know. Roboto is a good choice for the body

**Pull request merged**
