### PR TITLE
Use markdown for the roadmap

### PR DESCRIPTION
**Pull request by steren**
instead of an insane HTML table :)
Visually, the result is as much readable. But what matters is that the code editable much more easily.

localhost-12345-roadmap html

### CODE REVIEW

**Comment by steren** [comment]
A future PR will update the roadmap itself. But I want to convert it first to markdown.

**Comment by davidzchen** [comment]
Should we use a different sorting order for this since a good screenful of the roadmap has already been released? The previous layout mitigated this issue since the table was more concise.

**Comment by steren** [comment]
The table was barely more compact. Only the titles are adding space in the markdown version.

Should we have an "upcoming" and a "released" section?

**Comment by davidzchen** [comment]
> Should we have an "upcoming" and a "released" section?

SGTM

**Pull request merged**
