### PR TITLE
Add Tencent logo to companies using Bazel on the home page

### PR DESCRIPTION
**Pull request by dr-dime**
As many teams in Tencent are adopting Bazel, we would like to be listed
as one of the users on the Bazel homepage.

As the home page uses a 12 column system, it's not possible to add a new
logo next to the existing 6 logos. Therefore, we wrap the logos into two rows.

### CODE REVIEW

**Comment by aiuto** [comment]
Could you please send this from an account that is explicitly associated with Tencent.

**Comment by dr-dime** [comment]
Sure, I'll make sure the organization association is clear for this account.

**Comment by philwo** [comment]
LGTM in general, but Tony has a good point - let's wait for the organization to be linked to the account. :)

**Comment by dr-dime** [comment]
Ah, sorry. I thought my membership is public visible. Now it’s fixed.

PTAL.

**Comment by dr-dime** [comment]
@aiuto @philwo friendly ping.

**Comment by aiuto** [comment]
Your profile still does not link to Tencent.

**Comment by dr-dime** [comment]
@aiuto Done. Apparently they have a bot to toggle the organization visibility. It should be visible again now.

**Review by aiuto — APPROVED** [review]

**Pull request merged**
