### PR TITLE
Create 2021 roadmap, archive 2020 roadmap

### PR DESCRIPTION
**Pull request by gregestren**
Shoutouts to @WarkahScott , @juliexxia , @sdtwigg , @comius  github.com/philsc in 2020 "EOY Review" section.

### CODE REVIEW

**Comment by gregestren** [comment]
@aiuto - how should we update the license entry? https://bazel.build/roadmaps/configuration.html#features

**Review by katre — APPROVED** [review]

**Comment by aiuto** [comment]
I thought we were going to take down individual roadmaps and come up with a
single, integrated one.

**Comment by gregestren** [comment]
> I thought we were going to take down individual roadmaps and come up with a single, integrated one.

My first priority is keeping ongoing communication with the community about our focus and trajectories. I'm happy to fold that into a more consolidated approach whenever one is shovel-ready. In the meantime this is the only outlet we have that and I want to keep it reliable.

**Review by comius — APPROVED** [review]

**Comment by sventiffe** [comment]
@floriographygoth suggested to actually remove the entire section until our homework is done, but given that we're running behind I wonder if we should at least keep one subteam roadmap up to date.

**Comment by gregestren** [comment]
If you want to remove it, we should offer some input to the community what's going on, so they don't think we've just decided to drop offering roadmaps out of boredom. If so, I'd want to find an alternative medium for communication in the interim. Maybe a GitHub issue or GitHub project could do it.

But that's also shifting the same thing over to a different form.

**Pull request merged**
