### PR TITLE
Update the maintainers for the labels

### PR DESCRIPTION
**Pull request by laurentlb**

### CODE REVIEW

**Comment by laurentlb** [comment]
- According to @jhfield, @philwo's team own the remote execution parts.
- The Starlark label contains mostly issues around the Build API, which belongs to @lberki's team.
- The frontend team was disabanded (I've retriaged the open issues, the label is no longer used).

**Comment by laurentlb** [comment]
ping @philwo and @lberki

**Comment by laurentlb** [comment]
ping @philwo @lberki @jhfield 
It would be nice to resolve it this week.

The alternative is that I'll just remove my name from the page, but I'd rather avoid it.

**Comment by lberki** [comment]
Sorry for the delay. Approved!

**Pull request merged**
