### PR TITLE
Remove the "Getting Started" section on the front-page.

### PR DESCRIPTION
**Pull request by laurentlb**
- There's already a "Get Started" button at the top.
- Bazel is a multilanguage tool, this section was a bit misleading.

### CODE REVIEW

**Comment by laurentlb** [comment]
cc @laszlocsomor

**Comment by laszlocsomor** [comment]
LGTM

**Comment by laurentlb** [comment]
(I still need approval for this)

**Comment by laszlocsomor** [comment]
From whom?

**Comment by laurentlb** [comment]
> At least 1 approving review is required by reviewers with write access

**Pull request merged**
