### PR TITLE
Update Tweag blurb

### PR DESCRIPTION
**Pull request by rdbuckley**
Questions? Please email me at robert.buckley@tweag.io

### CODE REVIEW

**Comment by rdbuckley** [comment]
@googlebot I signed it!

**Comment by jin** [comment]
cc @hicksjoseph

**Comment by rdbuckley** [comment]
Who is a approving reviewer here?

**Comment by rdbuckley** [comment]
@aiuto Who is an approving reviewer? Noticed you removed a request for review with @mnarinsky.

**Comment by aiuto** [comment]
A number of people could approve, but I want to make sure @hicksjoseph reads it.

Can you give us a little turn around time? You sent this after 5pm US Eastern time last night, when all of the Bazel team was done for the day. Website fixes are not anyone's top priority right now.

**Comment by rdbuckley** [comment]
> A number of people could approve, but I want to make sure @hicksjoseph reads it.
> 
> Can you give us a little turn around time? You sent this after 5pm US Eastern time last night, when all of the Bazel team was done for the day. Website fixes are not anyone's top priority right now.

Only asked who since it was odd to see a an approval request removal.

**Comment by laurentlb** [comment]
@rdbuckley The change looked good to me, did you intentionally close the pull request?

**Comment by rdbuckley** [comment]
@laurentlb Thanks, I liked it to. Yes, closed intentionally.

**Comment by jin** [comment]
Sorry, I should have brought in more context when I plus'ed @hicksjoseph in, who's the PM driving the Bazel Experts program and would be the best approver for copy on the Bazel Experts page. 

Would you like to re-open the PR, @rdbuckley?

**Comment by rdbuckley** [comment]
Hi @jin, thanks for the note! Not interested in reopening.

**Pull request closed without merging**
