### PR TITLE
Windows,roadmap: reorganize, focus on Q3 goals

### PR DESCRIPTION
**Pull request by laszlocsomor**
Reorganize the Windows roadmap to improve
readability.

The new layout focuses on current goals, removes
the hard-to-read list hierarchy, replacing it with
headers and lists below them.

### CODE REVIEW

**Comment by laurentlb** [comment]
LGTM

**Comment by laszlocsomor** [comment]
Thanks for the quick review @laurentlb !

**Comment by laszlocsomor** [comment]
Waiting for @dslomov to review.

**Comment by laszlocsomor** [comment]
Actually, the contents are the same as before, I'm just restructuring the site, and I have an LGTM from @laurentlb , so I'll go ahead and merge.

**Pull request merged**
