### PR TITLE
Cleanup change to remove unused files.

### PR DESCRIPTION
**Pull request by davidzchen**
* Remove versions directory, which contains Bazel docs, which remain in the
  bazelbuild/bazel repository.
* Remove template files used only by the docs and blog sites.
* Add .gitignore
* Remove command-line-reference template files, which is only used by
  the docs site.

### CODE REVIEW

**Comment by davidzchen** [comment]
@steren - Can you please change the settings for this repository (and the bazel-blog repository) so that only Squash and Merge committing is enabled for pull requests?

**Comment by davidzchen** [comment]
Also, it looks like Issues is disabled for this repo. Is that intentional?

**Comment by steren** [comment]
Sure, these needed to be changes in the settings. Done

**Comment by davidzchen** [comment]
Thanks!

**Pull request merged**
